### ISSUE TITLE
Accept PRs for White Paper

### ISSUE THREAD

**Issue by hawkinsw** [ocsf/ocsf-docs#9]
Thank you for writing such an excellent white paper that introduces the schema so thoroughly. It is incredibly well written and complete. There are a few places where I think that I can contribute (editorially, of course -- I would never presume to change the content) and would love to submit PRs. 

I cannot seem to find the right place to do that. In fact, I am sure that using the `Issues` in this repo is not even the best place for this message -- I apologize.

I look forward to helping, if I can!

**Comment by pagbabian-splunk** [comment]
Hi sorry for such a long delay on this.  So far I have been republishing the paper with suggestions that have been brought in via different channels (Issues is fine).  However it might be better if I converted the original to .md format so that we can all more easily contribute with PRs etc.  In the mean time, you can add more detail to the Issues and I'll try to get them in.

**Comment by pagbabian-splunk** [comment]
I also enabled Discussions for this repo - it was an oversight not to have it set.  That's probably the best place to start, before we create Issues, which then can move to PRs.

**Comment by pagbabian-splunk** [comment]
@hawkinsw There is now a markdown file for the white paper.  We can certainly accept PRs.
